### ISSUE TITLE
invalid_content_type error message 

### ISSUE THREAD

**Issue by calciumdude** [gruijter/com.gruijter.facepp#19]
![Screenshot 2022-10-12 125555](https://user-images.githubusercontent.com/38105772/195325042-c743bb56-4d76-4f9c-9f08-6aa492441252.png)

what can be the reason for this error ?

in the log the following is entered :
2022-10-12 12:56:41 [log] no faces found in image Voordeur
unclosed server .s59824dbc

**Comment by gruijter** [comment]
I dont see an error in the log. The log says it cannot find a face in the image. That can be caused by bad image quality. Try sending the image to yourself to see what it actually looks like. But with Ring you only get a single snapshot, so chances are you will hardly ever get a good sbapshot suited for face recognition.
