### ISSUE TITLE
Log line: unclosed server

### ISSUE THREAD

**Issue by sossienl** [gruijter/com.gruijter.facepp#6]
Might not be an error, but more a question: 

I see "unclosed server .sda9b89dc " (last part changes) several times in my logs.

What does it mean?

**Comment by gruijter** [comment]
I have seen that also, but there is no reference where it is coming from. I suspect it is coming from Homey itself, and has something to do with the frontend (settings page) staying in an unknown state.

Close the settings page and restart the app. For me that resolves it.

But since I cannot pinpoint the issue, I have no clue how to solve it, or what bug to report to Athom.

**Comment by gruijter** [comment]
closing this because I do not know how to solve it
